### ISSUE TITLE
dd closing tags error

### ISSUE THREAD

**Issue by heatherlyall** [heatherlyall/link-card#1]
Markbot is telling me that my closing dd tags are missing even though I have them in the index? @thomasjbradley

**Comment by thomasjbradley** [comment]
The `dd` tag for Animalia is missing its slash.

**Comment by heatherlyall** [comment]
Thanks! It also says it's expected to see an h2 in the index but I also have one of those @thomasjbradley

**Comment by thomasjbradley** [comment]
It’s looking for an `<h2>` inside an `<a>` tag—which isn’t there.
The whole thing should be an `<a>` tag because it’s a link-card: one large link/button.

**Comment by heatherlyall** [comment]
I tried adding the a tag but it says that it violates the nesting rules @thomasjbradley

**Comment by thomasjbradley** [comment]
Where did you put the `<a>` tag?
Did you get rid of the `<ul>`? This isn’t a list.

**Comment by heatherlyall** [comment]
I put the a tag above the ul class

**Comment by heatherlyall** [comment]
I put the a tag above the ul class @thomasjbradley

**Comment by thomasjbradley** [comment]
Try getting rid of the `<ul>` & `<li>` because this whole thing isn’t a list.

**Comment by heatherlyall** [comment]
I tried that and it just completely got rid of the box that I had made is that supposed to happen? @thomasjbradley

**Comment by thomasjbradley** [comment]
Yep. Because `a` tags, by default, cannot have block tags within. To make it work you have to convert the `a` tag to a block element.

**Comment by heatherlyall** [comment]
I tried that but it still won't work :( @thomasjbradley

**Comment by thomasjbradley** [comment]
You mean this line of code, here?
https://github.com/heatherlyall/link-card/blob/gh-pages/css/main.css#L32

That won’t work because the `.link-card` **is** an `<a>` tag—but the selector says the “`<a>` tag is *inside* the `.link-card`”

**Comment by heatherlyall** [comment]
Okay the box appeared but it's not fitting the dimensions shown in the CSS @thomasjbradley

**Comment by thomasjbradley** [comment]
I think the `:hover` needs a little adjustment. Try deleting these lines:
https://github.com/heatherlyall/link-card/blob/gh-pages/css/main.css#L58-L62

**Comment by heatherlyall** [comment]
Okay so that's fixed, where do I put the padding, margins, border widths, etc. because it's not working in the a tag @thomasjbradley

**Comment by thomasjbradley** [comment]
There should only be 1 `<a>` tag on the website. Refer to this slide here that shows how to use a `<span>` tag to visually simulate the look of a button:
https://learn-the-web.algonquindesign.ca/courses/web-dev-1/link-patterns/#slide-8

**Comment by heatherlyall** [comment]
That fixed the smaller button, but theres still an 84% difference because of the size of the bigger button with the lists. The lists also seem to be in the incorrect font and I can't figure out why @thomasjbradley

**Comment by thomasjbradley** [comment]
*Re font—*

Only the heading is `Dosis`, the rest of the text is set in `Georgia`.

---

*Screenshots—*

I think the biggest difference right now is the colour of the button—it’s a very dark brown versus the beige in the screenshot.

**Comment by heatherlyall** [comment]
Okay changing the colour helped a lot it's only 27% now. How do I get the lines that divide everything up? @thomasjbradley

**Comment by thomasjbradley** [comment]
The lines are borders—but only on the top & bottom of elements.

**Comment by heatherlyall** [comment]
I tried putting the border top and bottom in but there's nothing appearing @thomasjbradley

**Comment by thomasjbradley** [comment]
Borders require 3 pieces of information: width, style & colour.

**Comment by heatherlyall** [comment]
I have all of those in and it still won't appear :( @thomasjbradley

**Comment by thomasjbradley** [comment]
Where is that in your code?

**Comment by heatherlyall** [comment]
it's in the div section of my css

**Comment by heatherlyall** [comment]
it's in the div section of my css @thomasjbradley

**Comment by thomasjbradley** [comment]
It should be written like this: `border-top: 3px solid #000`

**Comment by heatherlyall** [comment]
thanks! The last thing that I'm stuck on is the spacing of the dd and dt. It's too big and I'm in the extra help and the TA said to ask you about it cause she couldn't figure it out either @thomasjbradley

**Comment by thomasjbradley** [comment]
I have them both set to `width: 45%`—and make sure to remove the default `margin` from the `<dt>`

**Comment by heatherlyall** [comment]
@thomasjbradley Apparently markbot isn't happy with that, did I do the margin in the dt correctly?

**Comment by thomasjbradley** [comment]
Sorry—my fault. It’s the `<dd>` that needs its margin removed.

**Comment by heatherlyall** [comment]
That helped!! However the spacing between them is still making markbot unhappy, do I need to put padding? @thomasjbradley
